### ISSUE TITLE
Need build folder published to npm

### ISSUE THREAD

**Issue by chemzqm** [componentjs/outdated.js#1]
It's throwing error without generator support.
There is prepublish script but don't why the folder doesn't exists.

**Comment by jonathanong** [comment]
wow so confused. just updated 1.0.3 for nothing. i wonder what's going on

**Comment by chemzqm** [comment]
build folder not exist after running `npm install component-outdated2`

```
module.js:333
    throw err;
          ^
Error: Cannot find module './build'
    at Function.Module._resolveFilename (module.js:331:15)
    at Function.Module._load (module.js:273:25)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)
    at Object.<anonymous> (/Users/chemzqm/component-dev/notice/node_modules/component-outdated2/index.js:1:80)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Function.Module.runMain (module.js:490:10)
➜  component-outdated2 git:(master) ✗ ls
Makefile  README.md  index.js  lib  node_modules  package.json
```

**Comment by jonathanong** [comment]
Yeah I don't know why that folder isn't being published. It gets built and everything on my machine when publishing
